use_frameworks!

target 'HelloLanxinyiyi_Example' do
  pod 'HelloLanxinyiyi', :path => '../'

  target 'HelloLanxinyiyi_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
